import { CONTENT_SECURITY_POLICY_HEADER } from './csp.ts';
import { renderAllPages } from './render.ts';

/** Headers every host should send. A meta tag cannot send frame-ancestors or nosniff, so hosts that can, should. */
export const SECURITY_HEADERS: ReadonlyArray<readonly [string, string]> = [
  ['Content-Security-Policy', CONTENT_SECURITY_POLICY_HEADER],
  ['X-Content-Type-Options', 'nosniff'],
  ['Referrer-Policy', 'no-referrer'],
  ['Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=()'],
];

export interface SupportFile {
  /** Path from the repository root. */
  file: string;
  content: string;
}

/** Files that depend on the same sources as the pages: header configs for Netlify, Cloudflare Pages and Vercel, robots and sitemap. */
export function renderSupportFiles(siteUrl: string): SupportFile[] {
  const base = siteUrl.endsWith('/') ? siteUrl : `${siteUrl}/`;
  const headersFile =
    '# Generated by scripts/generate-pages.ts from src/site/csp.ts. Read by Netlify and Cloudflare Pages.\n' +
    '/*\n' +
    SECURITY_HEADERS.map(([name, value]) => `  ${name}: ${value}`).join('\n') +
    '\n/*.wasm\n  Content-Type: application/wasm\n';

  const vercel = {
    $schema: 'https://openapi.vercel.sh/vercel.json',
    cleanUrls: false,
    trailingSlash: true,
    headers: [
      {
        source: '/(.*)',
        headers: SECURITY_HEADERS.map(([key, value]) => ({ key, value })),
      },
    ],
  };

  const pages = renderAllPages(base);
  const urls = pages
    .map((page) => {
      const path = page.file.replace(/index\.html$/, '');
      const alternates = pages
        .filter((other) => other.kind === page.kind)
        .map(
          (other) =>
            `    <xhtml:link rel="alternate" hreflang="${other.lang}" href="${base}${other.file.replace(/index\.html$/, '')}"/>`,
        )
        .join('\n');
      return `  <url>\n    <loc>${base}${path}</loc>\n${alternates}\n  </url>`;
    })
    .join('\n');
  const sitemap =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
    `${urls}\n</urlset>\n`;

  return [
    { file: 'public/_headers', content: headersFile },
    { file: 'vercel.json', content: `${JSON.stringify(vercel, null, 2)}\n` },
    { file: 'public/robots.txt', content: `User-agent: *\nAllow: /\n\nSitemap: ${base}sitemap.xml\n` },
    { file: 'public/sitemap.xml', content: sitemap },
  ];
}
